set +x
docker stop $(docker ps -aq)
docker rm -f $(docker ps -aq)
rm -rf /tmp/controller-*
rm -rf /tmp/broker-*

# common setting
KAFKA_ACCOUNT=TaiJuWu
CLUSTER_ID=9knFxiAxLmWWZ0NnVqH5zx
IMAGE_NAME=kafka-19850-auto-join

# Controller setting
CONTROLLER_REVISION=KAFKA-19850-auto-join
CONTROLLER_PORT=17684
CONTROLLER_NODE_ID=$CONTROLLER_PORT
BOOTSTRAP_CONTROLLER=192.168.31.242:9093,192.168.31.242:17684,192.168.31.242:17683,192.168.31.242:17685
META_FOLDER=/tmp/controller-$CONTROLLER_PORT

# Broker setting
BROKER_REVERSION=KAFKA-19850-auto-join
BROKER_NODE_ID=12393
BROKER_PORT=$BROKER_NODE_ID
BOOTSTRAP_BROKER=192.168.31.242:12393
DATA_FOLDERS=/tmp/broker-$BROKER_PORT

# start up controller (leader)
IMAGE_NAME=$IMAGE_NAME NODE_ID=$CONTROLLER_NODE_ID META_FOLDER=$META_FOLDER \
CLUSTER_ID=$CLUSTER_ID CONTROLLER_PORT=$CONTROLLER_PORT \
KAFKA_ACCOUNT=${KAFKA_ACCOUNT} KAFKA_REVISION=$CONTROLLER_REVISION ./docker/start_controller.sh \
BOOTSTRAP_CONTROLLER=$BOOTSTRAP_CONTROLLER
sleep 2

IMAGE_NAME=$IMAGE_NAME NODE_ID=$BROKER_NODE_ID BROKER_PORT=$BROKER_PORT DATA_FOLDERS=$DATA_FOLDERS \
CLUSTER_ID=$CLUSTER_ID KAFKA_REVISION=$BROKER_REVERSION \
KAFKA_ACCOUNT=${KAFKA_ACCOUNT} ./docker/start_broker.sh \
controller.quorum.bootstrap.servers=$BOOTSTRAP_CONTROLLER


IMAGE_NAME=$IMAGE_NAME BROKER_PORT=13923 \
CLUSTER_ID=$CLUSTER_ID KAFKA_REVISION=$BROKER_REVERSION \
KAFKA_ACCOUNT=${KAFKA_ACCOUNT} ./docker/start_broker.sh \
controller.quorum.bootstrap.servers=$BOOTSTRAP_CONTROLLER


### Controller_1 setting
CONTROLLER_PORT=17683 \
KAFKA_ACCOUNT=Apache \
CLUSTER_ID=9knFxiAxLmWWZ0NnVqH5zx \
IMAGE_NAME=${IMAGE_NAME} \
NODE_ID=${CONTROLLER_PORT} META_FOLDER=/tmp/controller-17683 \
CLUSTER_ID=${CLUSTER_ID} ACCOUNT=taijuwu \
KAFKA_ACCOUNT=${KAFKA_ACCOUNT} KAFKA_REVISION=${CONTROLLER_REVISION} \
./docker/start_controller.sh controller.quorum.bootstrap.servers=${BOOTSTRAP_CONTROLLER}

CONTROLLER_PORT=17685 \
KAFKA_ACCOUNT=Apache \
CLUSTER_ID=9knFxiAxLmWWZ0NnVqH5zx \
IMAGE_NAME=${IMAGE_NAME} \
NODE_ID=${CONTROLLER_PORT} META_FOLDER=/tmp/controller-17685 \
CLUSTER_ID=${CLUSTER_ID} ACCOUNT=taijuwu \
KAFKA_ACCOUNT=${KAFKA_ACCOUNT} KAFKA_REVISION=${CONTROLLER_REVISION} \
./docker/start_controller.sh controller.quorum.bootstrap.servers=${BOOTSTRAP_CONTROLLER}
