docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
rm -rf /tmp/*

CONTROLLER_PORT=17684
CLUSTER_ID=9knFxiAxLmWWZ0NnVqH5zx
META_FOLDER=/tmp/controller-trunk
DATA_FOLDERS=/tmp/broker-1
CONTROLLER_REVISION=4.1
BROKER_REVERSION=4.1
KAFKA_ACCOUNT=TaiJuWu

META_FOLDER=$META_FOLDER CLUSTER_ID=$CLUSTER_ID CONTROLLER_PORT=$CONTROLLER_PORT ACCOUNT=taijuwu \
KAFKA_ACCOUNT=${KAFKA_ACCOUNT} KAFKA_REVISION=$CONTROLLER_REVISION ./docker/start_controller.sh

DATA_FOLDERS=$DATA_FOLDERS CLUSTER_ID=$CLUSTER_ID KAFKA_REVISION=$BROKER_REVERSION ACCOUNT=taijuwu \
KAFKA_ACCOUNT=${KAFKA_ACCOUNT} ./docker/start_broker.sh \
controller.quorum.bootstrap.servers=192.168.31.242:$CONTROLLER_PORT