docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
rm -rf /tmp/*

# common setting
KAFKA_ACCOUNT=Apache
CLUSTER_ID=9knFxiAxLmWWZ0NnVqH5zx
IMAGE_NAME=kafka-trunk

# Controller setting
CONTROLLER_PORT=17684
CONTROLLER_NODE_ID=15660
META_FOLDER=/tmp/controller-${CONTROLLER_NODE_ID}-$CONTROLLER_PORT
CONTROLLER_REVISION=trunk

# Broker setting
BROKER_REVERSION=trunk
BROKER_NODE_ID=1234
BROKER_PORT=12393
DATA_FOLDERS=/tmp/broker-$BROKER_NODE_ID-$BROKER_PORT

IMAGE_NAME=$IMAGE_NAME NODE_ID=$CONTROLLER_NODE_ID META_FOLDER=$META_FOLDER CLUSTER_ID=$CLUSTER_ID CONTROLLER_PORT=$CONTROLLER_PORT ACCOUNT=taijuwu \
KAFKA_ACCOUNT=${KAFKA_ACCOUNT} KAFKA_REVISION=$CONTROLLER_REVISION ./docker/start_controller.sh

IMAGE_NAME=$IMAGE_NAME NODE_ID=$BROKER_NODE_ID BROKER_PORT=$BROKER_PORT DATA_FOLDERS=$DATA_FOLDERS CLUSTER_ID=$CLUSTER_ID KAFKA_REVISION=$BROKER_REVERSION ACCOUNT=taijuwu \
KAFKA_ACCOUNT=${KAFKA_ACCOUNT} ./docker/start_broker.sh \
controller.quorum.bootstrap.servers=192.168.31.242:$CONTROLLER_PORT


## Controller_1 setting
#CONTROLLER_PORT=17684 \
#KAFKA_ACCOUNT=Apache \
#CLUSTER_ID=9knFxiAxLmWWZ0NnVqH5zx \
#CONTROLLER_PORT_1=15684 \
#CONTROLLER_NODE_ID_1=14662 \
#META_FOLDER_1=/tmp/controller-${CONTROLLER_NODE_ID_1}-$CONTROLLER_PORT_1 \
#CONTROLLER_REVISION_1=trunk \
#\
#NODE_ID=$CONTROLLER_NODE_ID_1 META_FOLDER=$META_FOLDER_1 CLUSTER_ID=$CLUSTER_ID CONTROLLER_PORT=$CONTROLLER_PORT_1 ACCOUNT=taijuwu \
#KAFKA_ACCOUNT=${KAFKA_ACCOUNT} KAFKA_REVISION=$CONTROLLER_REVISION_1 \
#./docker/start_controller.sh controller.quorum.bootstrap.servers=192.168.31.242:$CONTROLLER_PORT
